### ISSUE TITLE
Plans for a migration tool similar to go-pg's?

### ISSUE THREAD

**Issue by elliotcourant** [uptrace/bun#1]
Do you have any plans to make a migration tool similar to what you did with go-pg? It would be nice to have an orm that also supported a tool like that easily that could be used with multiple databases. Maybe even database specific migrations?

Like SQLite requires a clause to enable foreign keys, so it wouldn't make sense to run such a script against a PostgreSQL database.

**Comment by vmihailenco** [comment]
Yes, but I am considering using the ideas from https://github.com/robinjoseph08/go-pg-migrations since it looks like a more robust approach.

>Like SQLite requires a clause to enable foreign keys, so it wouldn't make sense to run such a script against a PostgreSQL database.

I hope that hooks and specialized queries to create/drop columns/indexes will address this. I've tried to document the plan at https://github.com/uptrace/bun/issues/2.

**Comment by vmihailenco** [comment]
Should be done - see https://github.com/uptrace/bun/tree/master/example/migrate
