### ISSUE TITLE
how do i exec multiple queries as a single query?

### ISSUE THREAD

**Issue by qonn** [uptrace/bun#1001]
I'm using bun with mssql driver, trying to do something simple such as inserting but can't figure out how exactly. Using .Returning("SCOPE_IDENTITY()") doesn't seem to be working properly with mssql.

```go
type Person struct {
  bun.BaseModel `bun:"table:Person,alias:p"`

  PersonID int `bun:"PersonID,pk,autoincrement"`
  Name string `bun:"Name"`
}

// ...

entity := &Person{Name:"John Doe"}
personid := 0
err := db.NewInsert().Model(entity).Scan(context.Background(), &personid) // <-- how do i do that here?
```

sql that I'm trying to achieve is as below:

```sql
INSERT INTO Persons (Name) VALUES ('John Doe'); SELECT SCOPE_IDENTITY()
```

**Comment by bevzzz** [comment]
Hi @qonn! You want to do:

```go
db.NewInsert().Model(entity).Returning("PersonID").Scan(context.Background, &personid)

// Afaik, you could also `.Scan(ctx)`, in which case the ID will be scanned directly into `entity.PersonID`
```

to get the ID of the newly inserted Person instead of  using `scope_identity()`.

The reason the query wouldn't work correctly is that, in case of MSSQL, `.Returning("my_column")` appends [`OUTPUT INSERTED.my_column`](https://learn.microsoft.com/en-us/sql/t-sql/queries/output-clause-transact-sql?view=sql-server-ver16#inserted) to the query. Passing something that's not a valid column name would result in a broken SQL statement (i.e. `OUTPUT INSERTED.SCOPE_IDENTITY()`)

**Comment by qonn** [comment]
Hi @bevzzz, Wonderful! your code example didn't seem to work at first. But I managed to get it working by changing `PersonID` to `INSERTED.PatientID`. 

So incase if anyone ever stumble upon this problem in the future, here is the working version:

```go
db.NewInsert().Model(entity).Returning("INSERTED.PersonID").Scan(context.Background(), &personid)
```
