### ISSUE TITLE
pgx driver example is wrong and not working

### ISSUE THREAD

**Issue by khanakia** [uptrace/bun#1012]
https://bun.uptrace.dev/postgres/#pgx
- First, the example is missing the import `"github.com/jackc/pgx/v5"`
- Getting this error `config.PreferSimpleProtocol undefined (type *pgx.ConnConfig has no field or method PreferSimpleProtocol)compiler[MissingFieldOrMethod](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#MissingFieldOrMethod)`

```
package main

import (
	"context"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/stdlib"
	"github.com/uptrace/bun"
	"github.com/uptrace/bun/dialect/pgdialect"
)

var db *bun.DB

func initDb() {
	config, err := pgx.ParseConfig("postgres://postgres:@localhost:5432/datadb?sslmode=disable")
	if err != nil {
		panic(err)
	}
	config.PreferSimpleProtocol = true

	sqldb := stdlib.OpenDB(*config)
	db = bun.NewDB(sqldb, pgdialect.New())
}
```

![Screenshot 2024-08-06 at 4 09 37 PM](https://github.com/user-attachments/assets/67b62ad7-afca-49ba-a5f0-86ce7f5147cc)

**Comment by arturo-villalpando** [comment]
Hello my friend, 

The problem was that **pgx V5** change how to manage de "PreferSimpleProtocol, you could search **DefaultQueryExecMode** inside the documentation: [](https://pkg.go.dev/github.com/jackc/pgx/v5#ConnectConfig)

Then for the new version, is not necessary any more to modify the configuration fox **pgsxpool** by default work with **QueryExecModeExec** that is necessary by bun.

`
package config

import (
	// Go
	"context"
	"fmt"
	"sync"

	// External
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/jackc/pgx/v5/stdlib"
	"github.com/uptrace/bun"
	"github.com/uptrace/bun/dialect/pgdialect"
)

var (
	once     sync.Once
	instance *bun.DB
)

// Initialize the database connection
func initializeDB(ctx context.Context, db_connection string) (*bun.DB, error) {
	// Open connection
	pool, err := pgxpool.New(ctx, db_connection)
	if err != nil {
		return nil, fmt.Errorf("unable to connect to database: %w", err)
	}
	// Ping database
	err = pool.Ping(ctx)
	if err != nil {
		return nil, fmt.Errorf("unable to ping database: %w", err)
	}
	// Log
	fmt.Println("Established a successful connection!")
	// Create a new Bun DB instance using the pgxpool connection
	sqldb := stdlib.OpenDBFromPool(pool)
	conn := bun.NewDB(sqldb, pgdialect.New())
	// Run connection
	return conn, nil
}

// GetDB returns a database connection instance
func GetDB(ctx context.Context, db_connection string) (*bun.DB, error) {
	var err error
	// Singleton to run the connection only once
	once.Do(func() {
		instance, err = initializeDB(ctx, db_connection)
	})
	if err != nil {
		return nil, err
	}
	// Return the instance
	return instance, nil
}
`
Then you could test your connection:

`
package config

import (
        // Go
	"context"
	"testing"

	// External
	"github.com/stretchr/testify/assert"
)

// TestGetDB tests the GetDB function
func TestGetDB(t *testing.T) {
	// Database connection configuration
	db_connection := "postgres://arturo:@localhost:5432/gatzi?sslmode=disable"
	// Cretae a context
	ctx := context.Background()
	// Get the database instance
	db, err := GetDB(ctx, db_connection)
	// Verifify that there were no errors
	assert.NoError(t, err, "Error connecting to the database")
	// Verifify that the database instance is null
	assert.NotNil(t, db, "The database instance is not null")
}
`

Best regards.
