### ISSUE TITLE
Relations: "on_delete" tag option and do I still need notnull?

### ISSUE THREAD

**Issue by frederikhors** [uptrace/bun#12]
With `go-pg` I had:

```go
type Player struct {
  // ... many columns

  ProfileID int       `pg:",notnull,on_delete:CASCADE"`
  Profile   *Profile  `pg:"rel:has-one"`
}
```

I changed it to:

```go
type Player struct {
  // ... many columns

  ProfileID int       `bun:",notnull,on_delete:CASCADE"`
  Profile   *Profile  `bun:"rel:has-one"`
}
```

But:

1. it writes in console:

    ```
    WARN: bun: 2021/05/28 23:48:25 Player.ProfileID has unknown tag option: "on_delete"
    ```
    
    Why?

1. do I need `notnull` in this line?

    ```go
    ProfileID int `bun:",notnull,on_delete:CASCADE"`
    ```

**Comment by vmihailenco** [comment]
>has unknown tag option: "on_delete"

Bun no longer automatically creates foreign keys and does not support `on_detele`, because it only worked for has-one relations. The new way is to specify `ForeignKey` when creating a table:

```go
_, err := db.NewCreateTable().
	Model((*Book)(nil)).
	ForeignKey(`("author_id") REFERENCES "users" ("id") ON DELETE CASCADE`)
	Exec(ctx)
if err != nil {
	panic(err)
}
```

See https://bun.uptrace.dev/guide/queries.html#creating-tables

>do I need notnull in this line?

Yes, `notnull` is used to specify `NOT NULL` SQL constraint.
