### ISSUE TITLE
Export bun.join

### ISSUE THREAD

**Issue by NathanBaulch** [uptrace/bun#128]
Any chance `bun.join` could be exported? Perhaps there's a good reason not to, but everything else in `bun.tableModel` is exported so I just thought I'd ask.

I realize my use-case is uncommon, but I have an ORM layer in my project that inspects certain queries before execution and dynamically adds joins. This was possible in `go-pg` because the `orm.TableModel` interface was exported, meaning I could call the `Join` func despite the unexported `orm.join` return value.

I agree that implementation details are best hidden, but it would be nice if I could still get to (and manipulate) the metadata for more advanced scenarios.

**Comment by NathanBaulch** [comment]
`SelectQuery.Relation` adds a join, but there are a couple of scenarios where I need to inspect query joins in my ORM layer.
1. To simulate `INNER JOIN` by adding a joined PK not null condition (see https://github.com/go-pg/pg/issues/1322).
2. To automatically select joined PKs so that related struct fields aren't nil if the selected field happens to be empty.

I also use `TableModel.Join` directly if I want to attempt to add a join without causing an error if not possible. The `Relation` func marks the query failed (`stickyErr`) and I have no easy way to check/recover from that.

Happy to elaborate with examples on any of the above.

**Comment by vmihailenco** [comment]
Well, we don't support introspection for queries (including joins), because it is hard to maintain and use correctly. The usual advice here is to maintain the state you need separately from Bun/go-pg and only use Bun API to construct queries. That is what I do at Uptrace to build a rather complex DSL to query database, e.g. `group by span.group_id | span.rate | span.error_pct | p50(span.duration) | p90(span.duration) | p99(span.duration)` is translated to a Bun query using existing public API. It is more practical than relying on Bun's internal state which is designed for a different purpose and is limited no matter how much internal guts we expose.

>To simulate INNER JOIN by adding a joined PK not null condition (see Why does Relation() use Left Outer Join instead of Inner Join? Isn't Inner Join faster? go-pg/pg#1322).

This is something we should address before releasing v1. I am considering adding `*bun.RelationQuery`

```go
q.Relation("Author", func(q *bun.RelationQuery) error {
    q.InnerJoin().Column("col1", "col2")
    return nil
})
```

**Comment by NathanBaulch** [comment]
Thanks for the thorough response, that makes sense.
Where's the best place to discuss minor issues as I migrate from go-pg?

**Comment by vmihailenco** [comment]
GitHub issues is the best place.

> I am considering adding *bun.RelationQuery

I've tried this but it does not look promising, because we need to duplicate all the methods from `SelectQuery`. All that to support `InnerJoin`.

An alternative could be adding `RelationInnerJoin` but that is awkward, does not scale, and does not make sense for has-many and m2m.

The most promising idea so far is to add `RelationQuery`:

```go
q.RelationQuery("name", func(q *bun.SelectQuery) *bun.SelectQuery) { return q }) // LEFT JOIN
q.RelationQuery("name", func(q *bun.SelectQuery) *bun.SelectQuery) { return q }, bun.WIthRelationInnerJoin()) // INNER JOIN
```

Or leave everything as is.
