### ISSUE TITLE
pgdriver error codes as consts

### ISSUE THREAD

**Issue by ellisonleao** [uptrace/bun#187]
Hey, thanks for this awesome lib!

I was wondering if it would be nice to have the pgdriver error code as consts, the same thing we have in the [pgerrcode lib](https://github.com/jackc/pgerrcode/blob/master/errcode.go#L7-L352).  I think it would add more flexibility on how we can handle errors over there.  Let me know if it makes sense and I can open a PR if you think it's worth

**Comment by vmihailenco** [comment]
That looks useful and we probably should just use that module instead of bundling it with Bun? pgx is one of the drivers officially supported by Bun so it should not be a problem...

Instead we could add more helpers like https://github.com/uptrace/bun/blob/master/driver/pgdriver/error.go#L24-L35, but nothing obvious comes to mind (except documenting it :)...

**Comment by ellisonleao** [comment]
> That looks useful and we probably should just use that module instead of bundling it with Bun?

I would agree on this one. I guess pgerrcode is already feature complete and you just need to document the error handling part somehow. Let me know if you need any help on this one

**Comment by vmihailenco** [comment]
Added an example to https://bun.uptrace.dev/guide/drivers.html#pgdriver
