### ISSUE TITLE
With Bun database becomes a real headache

### ISSUE THREAD

**Issue by tpoxa** [uptrace/bun#229]
The second week goes of mine "one day refactoring" from go-pg. 
Only negative emotions so far.  Database-related codebase increased approx up to 40%.

Most troubles are coming from:
* non having selectInsert. Cannot  select a model with its relation if the case if root object exists. I used it everywhere.
* absence of universal orm.Query (I built it dependently on the logic and executed it once)
* weird webhooks which can not easily modify dto. Who needs a modifier which modifies nothing. 

The only reason I migrate is having ModelTableExpr which was expected in v11 but it looks like it's abandoned now.

**Comment by vmihailenco** [comment]
This does not look like a problem with Bun, but a problem with migrating your app to Bun. If there are good patterns that Bun does not support, please share them and I will try to support them. Otherwise, this discussion will not be constructive and/or helpful.

>non having selectInsert. Cannot select a model with its relation if the case if root object exists. U used it everywhere.

I've replied at https://github.com/uptrace/bun/issues/186#issuecomment-932868906. Your use cases don't look valid and don't justify adding SelectOrInsert.

>absence of universal orm.Query (I built it dependently on the logic and executed it once)
>weird webhooks which can not easily modify dto. Who needs a modifier which modifies nothing.

Bun has different hooks and if your app heavily uses hooks then it can be hard to migrate. But it is hard to do anything with hook-based approach and that is why it is not recommended.

**Comment by tpoxa** [comment]
My App uses only what the API of go-pg is allowed to use. It does not matter how bad my patterns were. They did their job. What I am saying is that bun is not a replacement for go-pg. That is the point.

BTW
No Wrap or WrapWith either or mention of it here https://bun.uptrace.dev/guide/pg-migration.html
