### ISSUE TITLE
Heroku postgresql DB fails with `db postgres ping: FATAL #28000 no pg_hba.conf entry for host, ssl off`

### ISSUE THREAD

**Issue by frederikhors** [uptrace/bun#253]
URGENT: first time using Bun on Heroku today.

I'm using the default DATABASE_CONNECTION string Heroku creates, like this:

`postgres://user:password@ec2-xxx.eu-west-5.compute.amazonaws.com:5432/DBNAME`

And this code:

```go
func NewBunDB(database_connection_string string) *bun.DB {
	dbPG := sql.OpenDB(pgdriver.NewConnector(pgdriver.WithDSN(database_connection_string)))

	dbBunPG := bun.NewDB(dbPG, pgdialect.New())

  err := dbBunPG.Ping()
  if err != nil {
    return fmt.Errorf("db postgres ping: %w", err)
  }

	return dbBunPG
}
```

And the error is scary!

`db postgres ping: FATAL #28000 no pg_hba.conf entry for host \"172.XX.XX.XX\", user \"USERNAME\", database \"DBNAME\", SSL off`

**What does this mean?**

**Comment by frederikhors** [comment]
Why are you using InsecureSkipVerify here: https://github.com/uptrace/bun/blob/5058064b8c5d7b99d4d149a84d1fec7a71507dac/driver/pgdriver/config.go#L223?

**Comment by elliotcourant** [comment]
I'm not sure if its exactly the same as elsewhere I've seen; but just because `InsecureSkipVerify` is true does not mean that it's not still using TLS.

It just means that if you are connecting to the database directly via an IP like `10.0.0.12` but the TLS certificate for the server is for `aservername-us-east-1.elb.awscloud.com` or something like that. It won't complain about the hostname. And the connection could still use TLS.

When InsecureSkipVerify is false; it requires that the hostname you are using matches the hostname in the certificate of the server exactly. Any difference in the hostname or any other parts of the certificate that might not be "trustworthy" (like the server or client certificate being issued from a non-trusted authority) would result in an error.

If you need it to be string and properly secure; you should use the `case "verify-ca", "verify-full":` options for TLS.

But it looks like the error you are seeing is infact due to trying to use TLS but not being able to. I would recommend trying to connect to the database using `sslmode=disable` and see if that works (if thats acceptable).

**Comment by frederikhors** [comment]
Thanks for you great answer. This is the first time I have this issue. Until now with go-pg or gorm I never had. Two cases:

- go-pg is using skipverify or something else;
- I'm not encrypting my DB connection: WOW!!!

I don't know if I should use `sslmode=disable` with heroku, maybe they use internal network and it's fine to do so.

I repeat, it's the first time it happens to me because I'm using bun for the first time.

**Comment by vmihailenco** [comment]
If you suspect a problem with pgdriver, try to replace it with pgx and check if the problem goes away - http://bun.uptrace.dev/guide/drivers.html#pgx. AFAIK there is no difference in how pgdriver/go-pg handle SSL connections.

>FATAL #28000 no pg_hba.conf entry for host, ssl off

Looks like an issue with pg_hba.conf . Check if the host `172.XX.XX.XX` is there and PostgreSQL was restarted properly.

**Comment by frederikhors** [comment]
It works with `go-pg` because there is an `if`:

`go-pg` (https://github.com/go-pg/pg/blob/v10/options.go#L219-L232):

```go
if sslMode, ok := query["sslmode"]; ok && len(sslMode) > 0 {
  switch sslMode[0] {
  case "verify-ca", "verify-full":
    options.TLSConfig = &tls.Config{}
  case "allow", "prefer", "require":
    options.TLSConfig = &tls.Config{InsecureSkipVerify: true} //nolint
  case "disable":
    options.TLSConfig = nil
  default:
    return nil, fmt.Errorf("pg: sslmode '%v' is not supported", sslMode[0])
  }
} else {
  options.TLSConfig = &tls.Config{InsecureSkipVerify: true} //nolint
}
```

`bun` (https://github.com/uptrace/bun/blob/master/driver/pgdriver/config.go#L238-L247):

```go
switch sslMode := q.string("sslmode"); sslMode {
case "verify-ca", "verify-full":
  opts = append(opts, WithTLSConfig(new(tls.Config)))
case "allow", "prefer", "require":
  opts = append(opts, WithTLSConfig(&tls.Config{InsecureSkipVerify: true}))
case "disable", "":
  // no TLS config
default:
  return nil, fmt.Errorf("pgdriver: sslmode '%s' is not supported", sslMode)
}
```

What is the correct way?

Convention over configuration?

**Comment by frederikhors** [comment]
Can you please release it? I cannot use master branch.

**Comment by vmihailenco** [comment]
Release v1.0.13

**Comment by frederikhors** [comment]
I'm sorry, @vmihailenco. This still doesn't work with bun v1.0.13. 😢

**Comment by frederikhors** [comment]
Same error.

**Comment by frederikhors** [comment]
It works! The problem was me!
