### ISSUE TITLE
bad connection or unexpected message

### ISSUE THREAD

**Issue by jpascal** [uptrace/bun#605]
I just try select from goroutines inside opened transaction and got ths error: 
`pgdriver: Next: unexpected message '\x00'`

Then I use pgx driver i got error:
`driver: bad connection`

**Comment by 54M5M17H** [comment]
@jpascal were you able to resolve this issue? We're seeing the same thing

**Comment by vmihailenco** [comment]
@54M5M17H you can try to replace pgdriver with pgx and see if the problems goes away https://bun.uptrace.dev/postgres/#pgx

**Comment by john8329** [comment]
Some additional info that might be useful to others. In my case it happened because I was executing queries while iterating an open row in a transaction. Basically the iteration needs to be finished, and *then* you can do other queries, or you have to do everything under the same transaction. There's some black magic there, but it has to do with these things.
