### ISSUE TITLE
model doesn't not include `has-many` relation in AfterSelect

### ISSUE THREAD

**Issue by TheDhejavu** [uptrace/bun#855]
## Description
model doesn't not include `has-many` relation in AfterSelect

```go
type Content struct {
	Base
	HasCriteria      bool  `bun:"-"`

	Criterias   [ ]*Criteria      `bun:"rel:has-many,join:id=content_id"`
}

type Criteria struct {
	Base
	ContentID     int
}


var _ bun.AfterSelectHook = (*Gate)(nil)

func (c *Content) AfterSelect(ctx context.Context, query *bun.SelectQuery) error {
	if len(gcCriterias) > 0 {
		c.HasCriteria = true
	}
	return nil
}
```

## Query
```go
err = pg.NewSelect().Model(&newGate).Relation("Criterias").Scan(context.Background())
```

**Comment by kmott** [comment]
Long-time `go-pg` user here--I ran into this same issue as well, only way around it was to walk my list of results, and make a modification before returning the slice to the caller.  Gross--but it works, for now.

I originally thought `AfterScanRow` would work (since your marshaling each row into a slice of `Model`), but that hook never seemed to fire when I configured it on my `Model`.
