### ISSUE TITLE
when I use query inside RunInTx, ERROR: relation "xxx" does not exist (SQLSTATE=42P01

### ISSUE THREAD

**Issue by HelloYLee** [uptrace/bun#874]
bun version: v1.1.14
postgresql15

In Test Mode,  I created the postgresql table with temp mode(bun.DB.NewCreateTable().IfNotExists().Temp()).
When I run query in RunInTx(use bun.DB.NewSelect().Model(mode).Scan(ctx))
I got an error " ERROR: relation "xxx" does not exist (SQLSTATE=42P01"
It can be fixed if I use bun.Tx.NewSelect().... to query, but I don't know if that is a bug or not
bun.DB works fine if I create table with normal mode.
bun.DB also works fine if I use it outside bun.DB.RunInTx()

**Comment by awiz911** [comment]
Seems like I ran into similar problem. But mine is migration related in tests. Preparing test db for test mode and it fails. Works perfect in normal mode. Problem was: because migration naming is date based my new migration for 2023070813000_bla got higher then previous migration from 20232507130000_init and test tries to run it first. Why can not it be simple 001_init, 002_some_changes and so on to avoid this problem (
