### ISSUE TITLE
 db.NewCreateTable with `bun:",pk,autoincrement"` did not create table   sqlite_sequence

### ISSUE THREAD

**Issue by tablecell** [uptrace/bun#929]
```
package main

import(
"fmt"
"context"
    "database/sql"
     "github.com/uptrace/bun"
  "github.com/uptrace/bun/driver/sqliteshim"
"github.com/uptrace/bun/dialect/sqlitedialect"
)

type User struct {
 bun.BaseModel `bun:"table:users,alias:u"`
 ID	 int64  `bun:",pk,autoincrement"`
 Name string


}
func main(){
ctx:=context.Background()
sqldb, err := sql.Open(sqliteshim.ShimName, "test.db")  // "file::memory:?cache=shared"
if err != nil {
	panic(err)
}
db := bun.NewDB(sqldb, sqlitedialect.New())
 fmt.Println(db)
// user := &User{Name: "admin"}

ret, err := db.NewCreateTable().Model((*User)(nil)).Exec(ctx)
fmt.Println(ret,err )
}

```
generated create table  sql is:
```
CREATE TABLE "users" ("id" INTEGER NOT NULL, "name" VARCHAR, PRIMARY KEY ("id"));
```
there is no " autoincrement "

**Comment by bevzzz** [comment]
As far as I can tell, the reason the sequence was not created is that in SQLite you get unique autoincremented ID column (called `ROWID`) for any table that has `INTEGER PRIMARY KEY` column in it. 

References:   
- https://www.sqlite.org/lang_createtable.html#rowid (Section **5. ROWID**) 
- https://stackoverflow.com/a/7906029/14726116

That being said, there _is_ a [dedicated `AUTOINCREMENT` keyword](https://www.sqlite.org/autoinc.html) in SQLite, which ensures that the next ROWID is _is at least one larger than the largest ROWID that has ever before existed in that same table_.   

I imagine that the current lack of support for it in `bun` was due to the default mechanism fulfiling most of the requirements you'd have for an autoincremented column.  You're right in that it'd make sense if `bun:",autoincrement"` created the sequence instead of silently falling back to `ROWID`.  

Looks like a small change, I'll try to come up with a PR for this.
