### ISSUE TITLE
model tag "alt" don't work

### ISSUE THREAD

**Issue by emileFRT** [uptrace/bun#954]
The [documentation](https://bun.uptrace.dev/guide/models.html#struct-tags) states that bun:"alt:alt_name" is a valid struct tag, but i get `WARN: bun: [.. ]has unknown tag option: "alt"` when trying to use it.
I don't see it listed as a field option in the function [isKnownFieldOption](https://github.com/uptrace/bun/blob/master/schema/table.go#L913) where there is an "alias" option that i do not understand for fields.
I'm willing to try to fix it if it's indeed a bug

**Comment by vallahaye** [comment]
Hello everyone,

I'm facing the same problem. I had planned to use `"alt"` annotations to implement generic repositories but unfortunately this has to be put aside until this problem is solved.
I've had a look at the linked PR and the fix seems very straightforward. Do you have any idea when it might be merged?

Thanks in advance, Bun is an excellent software!
