### ISSUE TITLE
can't scan 1 (float32) into float32

### ISSUE THREAD

**Issue by nasa1024** [uptrace/bun#993]
## what should i fix this error?
* model
```
type ScriptCategory struct {
	bun.BaseModel `bun:"script_category,alias:sc" json:"-"` 

	Id         int64   `bun:"id,pk" json:"id"`  
	Name       string  `bun:"name" json:"name"` 
	Sort       float32 `bun:"sort" json:"sort"`
	BaseFields `json:"-"`
}
```
* sql
```
CREATE TABLE `script_category` (
  `id` bigint(20) NOT NULL,
  `name` varchar(255) NOT NULL DEFAULT '',
  `sort` float NOT NULL DEFAULT '0' ,
  `created_at` int(11) unsigned NOT NULL DEFAULT '0' ,
  `updated_at` int(11) unsigned NOT NULL DEFAULT '0' ,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ;
```
* function
```
func QueryCategory(ctx context.Context, db *bun.DB) (list []model.ScriptCategory, err error) {
	err = db.NewSelect().Model(&model.ScriptCategory{}).
		ColumnExpr("sc.id, sc.name, sc.sort").
		Order("sort asc").
		Scan(ctx, &list)
	if err != nil {
		err = fmt.Errorf("NewSelect ScriptCategory: %v", err)
		return
	}
	return
}
```
* error log
```
[bun]  10:34:57.703   SELECT               19.081ms  SELECT sc.id, sc.name, sc.sort FROM `script_category` AS `sc` ORDER BY `sort` asc 	  *fmt.wrapError: sql: Scan error on column index 2, name "sort": bun: can't scan 1 (float32) into float32 
```

**Comment by CL-Jeremy** [comment]
Second this. In addition to this, for me at least, it doesn't work either if I try to scan `float32` into `float64`. I had to effectively leave the field out completely. I'm using Microsoft SQL Server for that matter (I'll have to check which exact version with our IT department). I'd say this much that this is not limited to MySQL.

**Comment by CL-Jeremy** [comment]
Found out that the root problem in my case actually lies in https://github.com/denisenkom/go-mssqldb.

According to the spec, the scanner function in `database/sql` should always return the value in double precision, regardless of the precision of the original field. It might be somewhat counter-intuitive (since the logical value of the bits representation does get interpreted differently), but type casts from `float32` to `float64` then back to `float32` retains the precision, so there's nothing wrong with the go spec.

In [line 355](https://github.com/denisenkom/go-mssqldb/blob/103f0369fa02aac21aae282e4f7f81c903aba6be/types.go#L335), this conversion is missing, whereas in [line 396](https://github.com/denisenkom/go-mssqldb/blob/103f0369fa02aac21aae282e4f7f81c903aba6be/types.go#L396) and other cases, the functions comply to the go spec. Adding the needed type cast in line 355 solves my issue.

I suppose that it probably makes more sense to look at https://github.com/go-sql-driver/mysql for your issue.
